import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class PrivacyPolicy extends StatefulWidget {
  const PrivacyPolicy({super.key});

  @override
  State<PrivacyPolicy> createState() => _PrivacyPolicyState();
}

class _PrivacyPolicyState extends State<PrivacyPolicy> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: const Color(0xffa0cf1a),
        title:  Text(
          'Privacy Policy',
          style: GoogleFonts.habibi(
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body:  SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Last updated: August 08, 2024\n',
              style: GoogleFonts.habibi(fontWeight: FontWeight.bold, fontSize: 16),
            ),
            Text(
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n'
                  'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.\n\n'
                  'Interpretation and Definitions\n'
                  'Interpretation\n'
                  'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\n'
                  'Definitions\n\n'
                  'Account means a unique account created for You to access our Service or parts of our Service.\n\n'
                  'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n\n'
                  'Application refers to Click Me, the software program provided by the Company.\n\n'
                  'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Click Me.\n\n'
                  'Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.\n\n'
                  'Country refers to: Uttar Pradesh, India\n\n'
                  'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n\n'
                  'Personal Data is any information that relates to an identified or identifiable individual.\n\n'
                  'Service refers to the Application or the Website or both.\n\n'
                  'Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n\n'
                  'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n\n'
                  'Website refers to Click Me, accessible from clinkme.\n\n'
                  'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.\n\n'
                  'Collecting and Using Your Personal Data\n'
                  'Types of Data Collected\n\n'
                  'Personal Data\n'
                  'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n\n'
                  'Email address\n'
                  'First name and last name\n'
                  'Phone number\n'
                  'Address, State, Province, ZIP/Postal code, City\n'
                  'Usage Data\n\n'
                  'Usage Data\n'
                  'Usage Data is collected automatically when using the Service.\n\n'
                  'Usage Data may include information such as Your Device\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\n'
                  'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.\n\n'
                  'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.\n\n'
                  'Information Collected while Using the Application\n'
                  'While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:\n\n'
                  'Information regarding your location\n'
                  'We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company\'s servers and/or a Service Provider\'s server or it may be simply stored on Your device.\n\n'
                  'You can enable or disable access to this information at any time, through Your Device settings.\n\n',
              style: GoogleFonts.habibi(

              ),
            ),
            // Add more sections as necessary...
          ],
        ),
      ),
    );
  }
}
